# Generated by Django 4.0.4 on 2022-06-04 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=20, verbose_name='全名')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='头衔')),
                ('avatar', models.ImageField(default='avatars/avatar.png', upload_to='avatars', verbose_name='头像')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='手机')),
                ('wechat', models.CharField(blank=True, max_length=50, verbose_name='微信')),
                ('qq', models.CharField(blank=True, max_length=50, verbose_name='QQ')),
                ('email', models.CharField(blank=True, max_length=120, verbose_name='邮箱')),
                ('url', models.URLField(blank=True, max_length=250, verbose_name='网站')),
                ('github', models.URLField(blank=True, max_length=250, verbose_name='GitHub')),
                ('bio', models.TextField(blank=True, verbose_name='简介')),
                ('hits', models.IntegerField(default=0, verbose_name='点击')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '个人资料',
                'verbose_name_plural': '个人资料',
            },
        ),
    ]
